code --install-extension christianalexander.flip
code --install-extension deibit.devdocs
code --install-extension drcika.apc-extension
code --install-extension eamodio.gitlens
code --install-extension EthanSK.restore-terminals
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension pmndrs.pmndrs
code --install-extension ryuta46.multi-command
code --install-extension s-nlf-fh.glassit
code --install-extension vscodevim.vim
code --install-extension VSpaceCode.whichkey
code --install-extension yummygum.city-lights-icon-vsc